### ISSUE TITLE
Issue with loading session values after upgrading to 0.11.4

### ISSUE THREAD

**Issue by TTD93** [roidrage/redis-session-store#134]
Hi, I've recently updated to ruby 3.1.0 and rails 7.0.4 and as part of that upgraded from version 0.11.3 to 0.11.4
When I try to load a session value now, a NoMethod error is being raised like so: 
` NoMethodError: undefined method '>' for true:TrueClass` 

Example code which blows up: 

```
session[:random_value] = 3 
session[:random_value].present?
```
```
Gemfile: 

ruby '3.1.0'

gem 'aws-sdk-s3'
gem 'bcrypt'
gem 'browser'
gem 'elasticsearch'
gem 'email_validator'
gem 'friendly_id'
gem 'haml'
gem 'jbuilder'
gem 'jwt'
gem 'typhoeus', '~> 1.4'
gem 'openid_connect', '~> 1.1'
gem 'pg'
gem 'puma'
gem 'rack-attack'
gem 'rails', '~> 7.0.4'
gem 'rails-i18n'
gem 'redis'
gem 'rest-client'
gem 'ruby-saml'
gem 'sidekiq'
gem 'faraday'
gem 'redis-session-store', '~>0.11.4'

group :development, :test do
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'guard'
  gem 'guard-minitest'
  gem 'priscilla'
end

group :development do
  gem 'brakeman'
  gem 'listen'
  gem 'rubocop'
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'web-console'
end

group :test do
  gem 'factory_bot_rails'
  gem 'fakeredis'
  gem 'minitest-spec-rails'
  gem 'mocha'
  gem 'webmock'
end
```
